[Триггеры и привязки](..\articles\azure-functions\functions-triggers-bindings.md) Функций Azure взаимодействуют с различными службами Azure. При интеграции с этими службами могут возникать ошибки, поступающие из API-интерфейсов базовых служб Azure. Ошибки также могут возникать при попытке взаимодействия с другими службами из вашего кода функции с использованием REST или клиентских библиотек. Чтобы избежать потери данных и обеспечить нормальное выполнение функций, очень важно обрабатывать ошибки из любого источника.

Для большинства триггеров не предусмотрен встроенный механизм повторных попыток, когда ошибка возникает во время выполнения функции. Два триггера, поддерживающие механизм повторных попыток, — это хранилище очередей Azure и хранилище BLOB-объектов. По умолчанию для этих триггеров повторные попытки выполняются до пяти раз. После пятой повторной попытки оба триггера записывают сообщение в специальную [очередь подозрительных сообщений](..\articles\azure-functions\functions-bindings-storage-queue.md#trigger---poison-messages). 

Во избежание потери данных триггера произойдет ошибка в функции, поэтому мы рекомендуем в коде функции использовать блоки try-catch для перехвата ошибок. При возникновении ошибки запишите сведения, передаваемые в функцию с помощью триггера, в специальную очередь "подозрительных" сообщений. Такой же подход использует и [триггер хранилища BLOB-объектов](..\articles\azure-functions\functions-bindings-storage-blob.md#trigger---poison-blobs). 

Таким образом можно сохранить события триггера, которые могут быть потеряны из-за ошибок, и повторно выполнить их позже с помощью другой функции для обработки сообщений из очереди подозрительных сообщений с использованием хранимых сведений.  